app:
  scheduler:
    interval: 10000
    link-to-be-checked-interval: 90000
  github:
    url: "https://api.github.com"
  stackoverflow:
    url: "https://api.stackexchange.com/2.3"
  bot:
    url: "http://localhost:8083"

springdoc:
  swagger-ui:
    path: "swagger-ui"

management:
  server:
    port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: password