app:
  bot:
    name: "tinkoff-bot"
    token: 5766916823:AAH-or1c4F7qXaKzvb8UeELQFmY474Gfbv0
  scrapper:
    url: "http://localhost:8080"
  rabbit-queue:
    exchange-name: updates
    queue-name: updates.queue
    routing-key: upd

springdoc:
  swagger-ui:
    path: "swagger-ui"

management:
  server:
    port: 8091
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: [ "info", "health", "prometheus" ]
      path-mapping:
        prometheus: metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes.enabled: true
      group:
        readiness.include: db
        liveness.include: ping
    prometheus:
      enabled: true
  metrics.tags:
    application: ${spring.application.name}

server:
  port: 8083

spring:
  application:
    name: "bot"
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass
